
#Feature Control
["feature control"]
	#Output info into the logs when generating Geolosys deposits
	debugWorldgen = false
	#Disable generation of Vanilla ores
	disableVanillaOreGen = true
	#The fallback materials which a Deposit can replace if they're not specified by the deposit itself
	#Format: Comma-delimited set of <modid:block> (see default for example)
	defaultReplacementMaterials = ["minecraft:stone", "minecraft:netherrack", "minecraft:sandstone", "quark:deepslate", "quark:smooth_basalt", "chisel:basalt/raw", "chisel:marble/raw", "create:gabbro", "create:dolomite", "create:limestone", "create:natural_scoria", "minecraft:granite", "minecraft:andesite", "minecraft:diorite", "create:weathered_limestone", "quark:marble", "byg:soapstone", "byg:scoria_stone", "byg:rocky_stone", "minecraft:netherrack", "minecraft:end_stone"]
	#Outputs really advanced info when generating deposits.
	advancedDebugWorldGen = false

#Prospecting Options
[prospecting]
	#Maximum samples that can generate with each pluton within a chunk
	#Range: 1 ~ 256
	maxSamplesPerChunk = 7
	#The upper limit of RNG for generating any pluton in a given chunk.
	#Larger values indicate further distance between plutons.
	#Range: > 1
	chunkSkipChance = 1
	#A list of <modid:block> that samples may not be placed on
	samplePlacementBlacklist = ["minecraft:ice", "minecraft:packed_ice", "minecraft:bedrock"]
	#Enable the prospector's pickaxe
	enableProPick = true
	#Allow the prospector's pick to get damaged
	enableProPickDmg = true
	#Max durability of a prospector's pick if damage is enabled
	#Range: > 1
	proPickDurability = 256
	#The range (depth) of the prospector's pick prospecting cycle
	#Range: > 1
	proPickRange = 10
	#The diameter of the prospector's pick prospecting cycle
	#Range: > 1
	proPickDiameter = 10
	#Give players a Field Manual if they haven't gotten one
	giveManual = false

#Mod-Compat Settings
[compat]
	#This will make it so that Platinum will drop Platinum AND Osmium
	enableOsmium = false
	#This will make it so that Platinum will ONLY drop Osmium
	enableOsmiumExclusively = false
	#This will make it so that Autunite will drop Uranium AND Yellorium
	enableYellorium = false
	#This will make is so that Coal has a rare chance of dropping sulfur
	enableSulfur = false

