"Enable Debug Output" = false
"Disable Ores" = ["minecraft:iron_ore", "minecraft:gold_ore", "minecraft:coal_ore", "minecraft:emerald_ore", "minecraft:redstone_ore", "minecraft:lapis_ore", "minecraft:diamond_ore", "minecraft:nether_quartz_ore", "minecraft:nether_gold_ore", "minecraft:ancient_debris"]
"Custom Ore" = []

