import crafttweaker.api.item.IIngredient;
import crafttweaker.api.item.IItemStack;

furnace.removeByName("immersiveengineering:crafting/ingot_copper_from_dust");
blastFurnace.removeByName("immersiveengineering:crafting/ingot_copper_from_dust_from_blasting");
furnace.removeByName("immersiveengineering:crafting/ingot_aluminum_from_dust");
blastFurnace.removeByName("immersiveengineering:crafting/ingot_aluminum_from_dust_from_blasting");
furnace.removeByName("immersiveengineering:crafting/ingot_lead_from_dust");
blastFurnace.removeByName("immersiveengineering:crafting/ingot_lead_from_dust_from_blasting");
furnace.removeByName("immersiveengineering:crafting/ingot_silver_from_dust");
blastFurnace.removeByName("immersiveengineering:crafting/ingot_silver_from_dust_from_blasting");
furnace.removeByName("immersiveengineering:crafting/ingot_nickel_from_dust");
blastFurnace.removeByName("immersiveengineering:crafting/ingot_nickel_from_dust_from_blasting");
furnace.removeByName("immersiveengineering:crafting/ingot_uranium_from_dust");
blastFurnace.removeByName("immersiveengineering:crafting/ingot_uranium_from_dust_from_blasting");
furnace.removeByName("immersiveengineering:crafting/ingot_constantan_from_dust");
blastFurnace.removeByName("immersiveengineering:crafting/ingot_constantan_from_dust_from_blasting");
furnace.removeByName("immersiveengineering:crafting/ingot_electrum_from_dust");
blastFurnace.removeByName("immersiveengineering:crafting/ingot_electrum_from_dust_from_blasting");
furnace.removeByName("immersiveengineering:crafting/ingot_steel_from_dust");
blastFurnace.removeByName("immersiveengineering:crafting/ingot_steel_from_dust_from_blasting");
furnace.removeByName("immersiveengineering:crafting/iron_ingot_from_dust");
blastFurnace.removeByName("immersiveengineering:crafting/iron_ingot_from_dust_from_blasting");
furnace.removeByName("immersiveengineering:crafting/gold_ingot_from_dust");
blastFurnace.removeByName("immersiveengineering:crafting/gold_ingot_from_dust_from_blasting");
furnace.removeByName("immersiveengineering:crafting/ingot_hop_graphite");
furnace.removeByName("pedestals:ingot_iron");
blastFurnace.removeByName("pedestals:ingot_iron_blasting");
furnace.removeByName("pedestals:ingot_gold");
blastFurnace.removeByName("pedestals:ingot_gold_blasting");
