import crafttweaker.api.item.IIngredient;
import crafttweaker.api.item.IItemStack;

#remove ingots from nuggets
craftingTable.removeByName("minecraft:gold_ingot_from_nuggets");
craftingTable.removeByName("minecraft:iron_ingot_from_nuggets");
craftingTable.removeByName("betterendforge:thallasium_ingot_from_thallasium_nuggets");
craftingTable.removeByName("betterendforge:terminite_ingot_from_terminite_nuggets");
craftingTable.removeByName("botania:conversions/manasteel_from_nuggets");
craftingTable.removeByName("botania:conversions/terrasteel_from_nugget");
craftingTable.removeByName("botania:conversions/elementium_from_nuggets");
craftingTable.removeByName("charm:netherite_nuggets/netherite_ingot_from_nuggets");
craftingTable.removeByName("create:crafting/materials/copper_ingot_from_compacting");
craftingTable.removeByName("create:crafting/materials/zinc_ingot_from_compacting");
craftingTable.removeByName("create:crafting/materials/brass_ingot_from_compacting");
craftingTable.removeByName("immersiveengineering:crafting/nugget_copper_to_ingot_copper");
craftingTable.removeByName("immersiveengineering:crafting/nugget_aluminum_to_ingot_aluminum");
craftingTable.removeByName("immersiveengineering:crafting/nugget_lead_to_ingot_lead");
craftingTable.removeByName("immersiveengineering:crafting/nugget_silver_to_ingot_silver");
craftingTable.removeByName("immersiveengineering:crafting/nugget_nickel_to_ingot_nickel");
craftingTable.removeByName("immersiveengineering:crafting/nugget_uranium_to_ingot_uranium");
craftingTable.removeByName("immersiveengineering:crafting/nugget_constantan_to_ingot_constantan");
craftingTable.removeByName("immersiveengineering:crafting/nugget_electrum_to_ingot_electrum");
craftingTable.removeByName("immersiveengineering:crafting/nugget_steel_to_ingot_steel");
#craftingTable.removeByName("mapperbase:steel_ingot");
craftingTable.removeByName("tconstruct:common/materials/copper_ingot_from_nuggets");
craftingTable.removeByName("tconstruct:common/materials/cobalt_ingot_from_nuggets");
craftingTable.removeByName("tconstruct:common/materials/slimesteel_ingot_from_nuggets");
craftingTable.removeByName("tconstruct:common/materials/tinkers_bronze_ingot_from_nuggets");
craftingTable.removeByName("tconstruct:common/materials/rose_gold_ingot_from_nuggets");
craftingTable.removeByName("tconstruct:common/materials/pig_iron_ingot_from_nuggets");
craftingTable.removeByName("tconstruct:common/materials/queens_slime_ingot_from_nuggets");
craftingTable.removeByName("tconstruct:common/materials/manyullyn_ingot_from_nuggets");
craftingTable.removeByName("tconstruct:common/materials/hepatizon_ingot_from_nuggets");
craftingTable.removeByName("tconstruct:common/materials/netherite_ingot_from_nuggets");
craftingTable.removeByName("geolosys:crafting/nuggets/copper_nugget_to_copper_ingot");
craftingTable.removeByName("geolosys:crafting/nuggets/tin_nugget_to_tin_ingot");
craftingTable.removeByName("geolosys:crafting/nuggets/silver_nugget_to_silver_ingot");
craftingTable.removeByName("geolosys:crafting/nuggets/lead_nugget_to_lead_ingot");
craftingTable.removeByName("geolosys:crafting/nuggets/aluminum_nugget_to_aluminum_ingot");
craftingTable.removeByName("geolosys:crafting/nuggets/nickel_nugget_to_nickel_ingot");
craftingTable.removeByName("geolosys:crafting/nuggets/platinum_nugget_to_platinum_ingot");
craftingTable.removeByName("geolosys:crafting/nuggets/zinc_nugget_to_zinc_ingot");
